Fix component cmake include guard issue
NXPmicro/mcux-sdk pull request #16
Opened 2021-04-07 03:27 UTC by mcuxsusan

Signed-off-by: Susan Su <susan.su@nxp.com>

**Prerequisites**
- [* ] I have checked latest main branch and the issue still exists.
- [* ] I did not see it is stated as known-issue in release notes.
- [ ] No similar GitHub issue is related to this change.
- [*] My code follows the commit guidelines of this project.
- [*] I have performed a self-review of my own code.
- [*] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

**Describe the pull request**

A clear and concise description for the change in this Pull Request and which issue is fixed. 

Fixes # (issue)

**Type of change** (please delete options that are not relevant):

- [*] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Tests**

* Test configuration (please complete the following information):
   - Hardware setting:
   - Toolchain:
   - Test Tool preparation:
   - Any other dependencies:
* Test executed
  Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
    - [*] Build Test
    - [ ] Run Test

2021-04-07 17:58 UTC, MaureenHelm requested changes
I have no objection to the changes, but I recommend adding more details to the commit message that explain why this change is necessary.

Your https://github.com/NXPmicro/mcux-sdk/issues/15#issuecomment-814189851 in the bug report indicates that the cmake version needs to be increased. If that's still true, it's hard to see amongst 9k lines of changes, so I recommend also noting this in the commit message or even doing it in a separate commit.

2021-04-08 10:37 UTC, mcuxsusan commented
Hi @MaureenHelm, thanks for the input. I will update PR and apply the change.

2021-04-13 13:20 UTC, mcuxsusan commented
Hello @MaureenHelm, excuse for my late update, may you please help check the update? Many thanks!

2021-04-15 22:21 UTC, MaureenHelm approved these changes

2021-04-16 09:12 UTC, merged