Feature/enable zephyr integration
NXPmicro/mcux-sdk pull request #37
Opened 2021-08-31 08:48 UTC by mcuxsusan

**Prerequisites**
- [ ] I have checked latest main branch and the issue still exists.
- [ ] I did not see it is stated as known-issue in release notes.
- [ ] No similar GitHub issue is related to this change.
- [ ] My code follows the commit guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

**Describe the pull request**

This pull request aims to enable zephyr hal nxp support using current mcux-sdk. Below integration has been done:
* Cmake build system integration: reference existing CMakeLists.txt of hal-nxp, include driver component according to the Kconfig setting in zephyr.
* Kconfig integration: For menuconfig item Modules->hal_nxp, menu MCUX SDK is listed when select to Use MCUX SDK, all available configuration for soc/drivers/components/middleware/utility are listed. 
simple build test of hello_world has been executed for all RT1xxx boards, RT6xx boards, lpcxpresso54114 and lpcxpresso55s69, shows now build issue.

Fixes # (issue)

**Type of change** (please delete options that are not relevant):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [*] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Tests**
* Test configuration (please complete the following information):
   - Hardware setting:
   - Toolchain:
   - Test Tool preparation:
   - Any other dependencies:
* Test executed
  Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
    - [*] Build Test
    - [ ] Run Test

2021-08-31 09:40 UTC, hakehuang commented
this is a huge change, do you have any documnets on those changes? @mcuxsusan

2021-08-31 09:44 UTC, hakehuang commented on drivers/lpsci/fsl_lpsci.c
> + * Copyright (c) 2015-2016, Freescale Semiconductor, Inc.
license correct?

2021-08-31 10:01 UTC, hakehuang requested changes
There are many Zephyr unrealted changes, can you split the PR into serval meanful ones, and let zephyr team review only zephyr related?

2021-08-31 10:01 UTC, hakehuang commented on devices/LPC54628/all_lib_device_LPC54628.cmake
> +mcux_include_as_kconfig(driver_ctimer)
put header file for each driver in a dedicated folder will make the the compiler seaching each folder again and again, which is not a good practise.

2021-08-31 11:34 UTC, mcuxsusan commented on CMSIS/kconfig.CMSIS
> +# Copyright 2021 NXP
In the Kconfig framework for MCUXpresso SDK, kconfig.xx is prepared in each category to describe the components in this directory only. Currently all the components are included in the configurable items of zephyr module hal_nxp according to the zephyr/Kconfig description, it's OK to remove some configuration items which are not used in zephyr. Currently the below relative kconfig.xx source are included in the kconfig file, please suggest which are not needed.

rsource "./devices/kconfig.socs"

rsource "./drivers/kconfig.drivers"

rsource "./CMSIS/kconfig.CMSIS"

rsource "./components/kconfig.components"

rsource "./devices/kconfig.devices"

rsource "./utilities/kconfig.utilities"

rsource "./middleware/kconfig.middleware"

2021-08-31 11:37 UTC, mcuxsusan commented on drivers/lpsci/fsl_lpsci.c
> + * Copyright (c) 2015-2016, Freescale Semiconductor, Inc.
I reused the lpsci driver in current hal_nxp module because the KL25 device which has lpsci driver, has been dropped from SDK release for a long time, so I simply used the verified lpsci driver in hal_nxp.

2021-08-31 11:38 UTC, mcuxsusan commented
> There are many Zephyr unrealted changes, can you split the PR into serval meanful ones, and let zephyr team review only zephyr related?

Sorry for the inconvenience, I will split the changes into separate commits.

2021-09-01 03:21 UTC, hakehuang commented on CMSIS/kconfig.CMSIS
> +# Copyright 2021 NXP
above list are all needed. but not all middleware is included

2021-09-08 07:32 UTC, hakehuang commented on zephyr/Kconfig
> +rsource "../Kconfig"
does Zephyr need use this?

2021-09-08 07:34 UTC, hakehuang commented on zephyr/hal_nxp.cmake
> +    ${CMAKE_CURRENT_LIST_DIR}/../CMSIS/Core/Include
remove this line

2021-09-08 07:43 UTC, hakehuang commented on zephyr/hal_nxp.cmake
> +include_driver_ifdef(CONFIG_ADC_MCUX_LPADC		lpadc	driver_lpadc)
each driver in one folder, why do this way?

2021-10-09 08:27 UTC, mcuxsusan commented on CMSIS/kconfig.CMSIS
> +# Copyright 2021 NXP
since we are not quite clear about the scenario for providing kconfig item up to zephyr, I will hold this kconfig commit and not put this into zephyr integration for now.

2021-10-09 08:30 UTC, mcuxsusan commented on zephyr/Kconfig
> +rsource "../Kconfig"
Thanks for highlighting this, I will hold this kconfig change and not put this into zephyr integration for now.

2021-10-11 04:05 UTC, dleach02 commented on components/kconfig.components
> +# SPDX-License-Identifier: BSD-3-Clause
'Kconfig.components'

2021-10-19 07:59 UTC, mcuxsusan commented
I also cherry-picked the commits in hal_nxp master for adding the needed driver/component to cmake build system. 
For other change of commits not included, listed them below:
- RT685: Update CTimer Clock API
- Adds MK66FN2 part device tree description
- mcux: devices: mke1xf: fix CAN_Type number of mailboxes
For these bugs will be firstly fixed in our internal develop repo, then deploy to the mcux-sdk, this way ensure the bug is fixed in the source. For the dts change, in current integration we did not include that part so the commit will be dropped.

2021-10-19 21:04 UTC, dleach02 commented on zephyr/hal_nxp.cmake
> +include_driver_ifdef(CONFIG_ADC_MCUX_LPADC		lpadc	driver_lpadc)
@hakehuang, I suspect this is because of how we maintain the drivers in the internal repository. We flattened this in the Zephyr NXP HAL but it is probably easier for keeping the external and internal repositories synchronized.

2021-12-14 05:55 UTC, mcuxsusan commented
Closed the PR because we have aligned to keep using [hal_nxp](https://github.com/zephyrproject-rtos/hal_nxp) to provide NXP HAL support for zephyr.  In the approach mcux-sdk is integrated to the existing [hal_nxp](https://github.com/zephyrproject-rtos/hal_nxp) as subtree to leverage the MCUXpresso SDK driver and device support. The PR to switch Zephyr HAL to use mcux-sdk in [hal_nxp](https://github.com/zephyrproject-rtos/hal_nxp) has been merged.

2021-12-14 05:55 UTC, closed without merging