Fix handling of TX complete interrupt in LPUART EDMA
NXPmicro/mcux-sdk pull request #47
Opened 2021-11-02 08:53 UTC by andresovela

This PR fixes a potential issue that could happen if the user of the driver enables other UART interrupts.

Signed-off-by: Andres O. Vela <andresovela@gmail.com>

**Prerequisites**
- [ ] I have checked latest main branch and the issue still exists.
- [ ] I did not see it is stated as known-issue in release notes.
- [ ] No similar GitHub issue is related to this change.
- [ ] My code follows the commit guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

**Describe the pull request**

A clear and concise description for the change in this Pull Request and which issue is fixed. 

Fixes # (issue)

**Type of change** (please delete options that are not relevant):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Tests**

* Test configuration (please complete the following information):
   - Hardware setting:
   - Toolchain:
   - Test Tool preparation:
   - Any other dependencies:
* Test executed
  Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. 
    - [ ] Build Test
    - [ ] Run Test

2021-11-02 08:56 UTC, mcuxsusan commented
Hi @andresovela , thanks for your prompt action on the sign-off issue. Our developer is checking the contribution and feedback may be delayed, appreciate for your understanding.

2021-11-03 06:51 UTC, mcuxsusan commented
Feedback from developer:
 _"When using the lpuart edma transactional layer, the interrupt is handled by the API LPUART_TransferEdmaHandleIRQ(the modified API in the PR) which is implemented inside the driver through double weak, the API is only dedicated to handle the transfer completion interrupt, so in LPUART_TransferCreateHandleEDMA the driver already disables all the interrupts. However if user enables any other interrupts after calling LPUART_TransferCreateHandleEDMA, the transfer flow may be aborted by mistake. The modification in the PR can prevent this from happening, we will also need to update document to remind user that it is forbidden to enable/disable any interrupts if using the transactional layer, regardless of the driver(uart/i2c.. etc) or the handling method(interrupt/edma)."_

2021-11-03 06:51 UTC, mcuxsusan requested changes
Please help update PR to fix the MISRA violation issue, thanks in advance.

2021-11-03 06:51 UTC, mcuxsusan commented on drivers/lpuart/fsl_lpuart_edma.c
> +    if (kLPUART_TransmissionCompleteFlag & LPUART_GetStatusFlags(base))
To avoid MISRA violation, please change to:
if (0U! = (kLPUART_TransmissionCompleteFlag & LPUART_GetStatusFlags(base)))

2021-11-03 22:35 UTC, andresovela commented on drivers/lpuart/fsl_lpuart_edma.c
> +    if (kLPUART_TransmissionCompleteFlag & LPUART_GetStatusFlags(base))
Fixed

2021-11-04 05:46 UTC, mcuxsusan approved these changes

2021-11-04 05:47 UTC, mcuxsusan commented
The change looks good, thanks again for your prompt action.

2021-11-04 05:47 UTC, merged